export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"
export const USER_SIGN = "USER_SIGN"
export const EMAIL_VERTIFICATION = "EMAIL_VERTIFICATION"
export const LOGIN_ERROR = "LOGIN_ERROR"


export const ADD_ARTICLE = "ADD_ARTICLE"
export const EDIT_ARTICLE = "EDIT_ARTICLE"
export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES"
export const GET_ARTICLE = "GET_ARTICLE"
export const GET_NONCONFIRMED_ARTICLES = "GET_NONCONFIRMED-ARTICLES"
export const SEARCH_ARTICLE = "SEARCH_ARTICLE"
export const GET_USER_ARTICLES = "GET_USER_ARTICLES"
export const GET_CATEGORY_ARTICLES = "GET_CATEGORY_ARTICLES"


export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"